# yaml-language-server: $schema=https://goreleaser.com/static/schema.json

version: 2
project_name: iccheck

before:
  hooks:
    - go mod download

builds:
  - binary: iccheck
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s
      - -w
      - -X github.com/salab/iccheck/pkg/utils/cli.version={{.Version}}
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - id: default
    format: binary
