name: Inconsistent Change Check

on:
  push:
    branches:
      - 'main'
  pull_request:

jobs:
  iccheck:
    name: Inconsistent Change Check
    runs-on: ubuntu-latest
    steps:
      - name: Install ICCheck
        run: |
          VERSION=$(curl -Lsf "https://api.github.com/repos/salab/iccheck/releases/latest" | jq -r '.tag_name')
          DOWNLOAD_URL="https://github.com/salab/iccheck/releases/download/$VERSION/iccheck_${VERSION//v/}_linux_amd64"
          curl -Lf "$DOWNLOAD_URL" -o iccheck
          chmod +x iccheck
          sudo install iccheck /usr/local/bin/

      - uses: actions/checkout@v4
        with:
          fetch-depth: '2'
      - name: Check for inconsistent changes
        run: iccheck --from "HEAD^" --to "HEAD" --format github
